### ISSUE TITLE
Config file example

### ISSUE THREAD

**Issue by lionel-bijaoui** [zillow/webpack-stats-duplicates#1]
Hello,
Can you provide an example of the config file or the use of whitelist in the CLI ?
I can't make whitelist work for some reason.
These don't seem to work:
```
webpack-stats-duplicates --whitelist './node_modules/vue-loader' stats.json
webpack-stats-duplicates --whitelist '/node_modules/vue-loader' stats.json
webpack-stats-duplicates --whitelist 'vue-loader' stats.json
```
Still output: 
```
...

Duplicate module vue-loader
        ./node_modules/vue-loader
        ./node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?sourceMap!./node_modules/vue-loader

...
```

Am I missing something ?
Thank you !

**Comment by stonebk** [comment]
Interesting, I haven't seen that format before. It will probably work if you use the entire string:

    ./node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!./node_modules/vue-style-loader!./node_modules/css-loader?sourceMap!./node_modules/vue-loader

If you attach your stats.json I can look into.

**Comment by lionel-bijaoui** [comment]
I'm using `vue-loader` so It may be the reason for this strange format? I also may have messed up the config? 🤷‍
I've attached stats.json (as a text file). Thank you for looking into that !
[stats.txt](https://github.com/zillow/webpack-stats-duplicates/files/803103/stats.txt)
