### ISSUE TITLE
Detects a duplicate module at the top level 

### ISSUE THREAD

**Issue by m3fawner** [zillow/webpack-stats-duplicates#3]
Duplicate module react-router found in webpack configuration 0
    ./node_modules/react-router
    ./node_modules/react-router

Top level dupes should never be able to exist, considering the top level modules are those that were resolved to satisfy several (or the project's) dependencies.

**Comment by stonebk** [comment]
@m3fawner, do you have the stats file that this occurred with?

**Comment by stonebk** [comment]
@m3fawner provide a stats file that reproduces and I'll reopen
